//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations.Schema;

namespace ProcessAccelerator.Core.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [Table("UserProfile")]
    public partial class UserProfile : Entity
    {
        public UserProfile()
        {
            this.webpages_UsersInRoles = new HashSet<webpages_UsersInRoles>();
        }
    
        public string UserName { get; set; }
        public Nullable<short> UserType { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string DisplayName { get; set; }
        public string EMailID { get; set; }
        public string MobileContact { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public Nullable<bool> IsGuest { get; set; }
        public Nullable<int> mstr_Process_LC_StatusID { get; set; }
        public Nullable<int> CreatedBy { get; set; }    
        public Nullable<DateTime> CreateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<DateTime> UpdateDate { get; set; }


        [ForeignKey("UserId")]
        public virtual ICollection<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual ICollection<tbl_org_proj_review_history> tbl_org_proj_review_history { get; set; }
        [ForeignKey("ID")]
        public virtual webpages_Membership webpages_Membership { get; set; } 
        [ForeignKey("EmployeeID")]
        public virtual tbl_org_employee tbl_org_employee { get; set; }
        [ForeignKey("ClientID")]    
        public virtual mstr_client mstr_client {get; set;}
    }
}
